import type { PreProviderResult, PreProviderRunArgs } from "../types.js";
import { runStockPortfolioProvider } from "../stock-portfolio/index.js";
import { loadStockPulseProviderConfig } from "./config.js";
import { analyzeStockPulseSeries } from "./analyzer.js";
import { isActiveWindow, openMarketsAt } from "./market.js";
import { buildScanUniverse, extractPortfolioSymbols } from "./symbols.js";
import { YahooStockPulseQuoteClient } from "./yahoo-client.js";
import type {
  StockPulseAlert,
  StockPulsePayload,
  StockPulsePortfolioRunner,
  StockPulseProviderConfig,
  StockPulseQuoteClient,
  StockPulseSymbol,
  StockPulseUniverseSymbol,
} from "./types.js";

export interface StockPulseProviderDeps {
  loadProviderConfig?: (name?: string) => StockPulseProviderConfig;
  portfolioRunner?: StockPulsePortfolioRunner;
  quoteClient?: StockPulseQuoteClient;
}

function sanitizeStockPulseError(err: unknown): string {
  const raw = err instanceof Error ? err.message : String(err);
  return raw
    .replace(/(validatekey=)[^&\s"']+/gi, "$1[redacted]")
    .replace(/(password|token|cookie|secret|session|account|customer|acc_id)\s*[:=]\s*[^,\s}]+/gi, "$1=[redacted]")
    .replace(/([A-Za-z0-9+/=_-]{24,})/g, "[redacted]")
    .slice(0, 800);
}

async function mapLimit<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const out: R[] = [];
  let index = 0;
  async function worker(): Promise<void> {
    while (index < items.length) {
      const current = items[index];
      index += 1;
      if (current !== undefined) out.push(await fn(current));
    }
  }
  const workers = Array.from({ length: Math.max(1, Math.min(limit, items.length)) }, () => worker());
  await Promise.all(workers);
  return out;
}

async function collectPortfolioSymbols(params: {
  args: PreProviderRunArgs;
  config: StockPulseProviderConfig;
  portfolioRunner: StockPulsePortfolioRunner;
  commits: Array<() => Promise<void>>;
  warnings: string[];
}): Promise<StockPulseSymbol[]> {
  if (!params.config.universe.include_portfolio || !params.config.portfolio_provider_config) return [];
  try {
    const result = await params.portfolioRunner({
      ...params.args,
      configName: params.config.portfolio_provider_config,
    });
    if (result.commit) params.commits.push(result.commit);
    return extractPortfolioSymbols(JSON.parse(result.text) as unknown, params.config.market_scope);
  } catch (err) {
    params.warnings.push(`portfolio source failed: ${sanitizeStockPulseError(err)}`);
    return [];
  }
}

async function collectUniverseSourceSymbols(
  config: StockPulseProviderConfig,
  quoteClient: StockPulseQuoteClient,
  warnings: string[],
): Promise<StockPulseUniverseSymbol[]> {
  if (!config.universe.include_sources || !quoteClient.getUniverseSymbols) return [];
  const symbols: StockPulseUniverseSymbol[] = [];
  for (const source of config.universe.sources) {
    try {
      symbols.push(...await quoteClient.getUniverseSymbols(source));
    } catch (err) {
      warnings.push(`universe source ${source.name} failed: ${sanitizeStockPulseError(err)}`);
    }
  }
  return symbols;
}

function marketTimezone(config: StockPulseProviderConfig, symbol: StockPulseSymbol): string {
  return config.markets[symbol.market]?.timezone ?? "Asia/Shanghai";
}

function buildPayload(params: {
  args: PreProviderRunArgs;
  config: StockPulseProviderConfig;
  activeWindowOk: boolean;
  openMarkets: StockPulsePayload["run_context"]["open_markets"];
  skipReason?: string;
  configuredSymbols: number;
  portfolioSymbols: number;
  universeSourceSymbols: number;
  scannedSymbols: number;
  failedSymbols: number;
  alerts: StockPulseAlert[];
  warnings: string[];
}): StockPulsePayload {
  return {
    generated_at: params.args.runAt.toISOString(),
    source: "stock-pulse",
    profile: params.args.configName ?? "default",
    market_scope: params.config.market_scope,
    run_context: {
      active_window_ok: params.activeWindowOk,
      open_markets: params.openMarkets,
      skipped: Boolean(params.skipReason),
      skip_reason: params.skipReason,
    },
    universe: {
      configured_symbols: params.configuredSymbols,
      portfolio_symbols: params.portfolioSymbols,
      universe_source_symbols: params.universeSourceSymbols,
      scanned_symbols: params.scannedSymbols,
      failed_symbols: params.failedSymbols,
    },
    alerts: params.alerts.sort((a, b) => {
      const severity = { urgent: 3, alert: 2, notice: 1 };
      return severity[b.severity] - severity[a.severity] || (b.z_score ?? 0) - (a.z_score ?? 0);
    }),
    warnings: params.warnings,
    usage_notes: [
      "This payload is generated by MiniClaw stock-pulse. It scans portfolio/watchlist/universe symbols only when both the user's active window and a configured market session are open.",
      "Alerts are deterministic: fixed return floors plus rolling intraday volatility, abnormal 5m-bar frequency, one-way bars, and z-score checks.",
      "Use alerts[] as the only anomaly list. If alerts is empty, say no abnormal move was detected; do not invent movers.",
      "This is analysis-only output. Do not provide trade instructions unless explicitly asked.",
    ],
  };
}

export async function runStockPulseProvider(
  args: PreProviderRunArgs,
  deps: StockPulseProviderDeps = {},
): Promise<PreProviderResult> {
  const configName = args.configName ?? "default";
  const config = (deps.loadProviderConfig ?? loadStockPulseProviderConfig)(configName);
  const quoteClient = deps.quoteClient ?? new YahooStockPulseQuoteClient();
  const portfolioRunner = deps.portfolioRunner ?? runStockPortfolioProvider;
  const warnings: string[] = [];
  const commits: Array<() => Promise<void>> = [];

  const activeWindowOk = isActiveWindow(args.runAt, config.active_window);
  const openMarkets = openMarketsAt(args.runAt, config.markets);
  if (!activeWindowOk || openMarkets.length === 0) {
    const payload = buildPayload({
      args,
      config,
      activeWindowOk,
      openMarkets,
      skipReason: !activeWindowOk ? "outside_user_active_window" : "no_configured_market_open",
      configuredSymbols: config.universe.symbols.length,
      portfolioSymbols: 0,
      universeSourceSymbols: 0,
      scannedSymbols: 0,
      failedSymbols: 0,
      alerts: [],
      warnings,
    });
    return { text: JSON.stringify(payload, null, 2) };
  }

  if (!config.universe.enabled) {
    const payload = buildPayload({
      args,
      config,
      activeWindowOk,
      openMarkets,
      skipReason: "universe_disabled",
      configuredSymbols: config.universe.symbols.length,
      portfolioSymbols: 0,
      universeSourceSymbols: 0,
      scannedSymbols: 0,
      failedSymbols: 0,
      alerts: [],
      warnings,
    });
    return { text: JSON.stringify(payload, null, 2) };
  }

  const portfolioSymbols = await collectPortfolioSymbols({
    args,
    config,
    portfolioRunner,
    commits,
    warnings,
  });
  const universeSourceSymbols = await collectUniverseSourceSymbols(config, quoteClient, warnings);
  const symbols = buildScanUniverse({
    scope: config.market_scope,
    configured: config.universe.symbols,
    portfolio: portfolioSymbols,
    universeSourceSymbols,
    includeWatchlist: config.universe.include_watchlist,
    includePortfolio: config.universe.include_portfolio,
    includeSources: config.universe.include_sources,
    openMarkets,
    maxSymbols: config.universe.max_symbols,
  });

  let failedSymbols = 0;
  const alerts = await mapLimit(symbols, config.quote.concurrency, async (symbol) => {
    try {
      const series = await quoteClient.getBars(symbol, config.quote);
      return analyzeStockPulseSeries({
        symbol,
        series,
        thresholds: config.thresholds,
        marketTimezone: marketTimezone(config, symbol),
      });
    } catch (err) {
      failedSymbols += 1;
      warnings.push(`${symbol.yahoo_symbol}: ${sanitizeStockPulseError(err)}`);
      return undefined;
    }
  });

  const payload = buildPayload({
    args,
    config,
    activeWindowOk,
    openMarkets,
    configuredSymbols: config.universe.symbols.length,
    portfolioSymbols: portfolioSymbols.length,
    universeSourceSymbols: universeSourceSymbols.length,
    scannedSymbols: symbols.length,
    failedSymbols,
    alerts: alerts.filter((alert): alert is StockPulseAlert => alert !== undefined),
    warnings,
  });

  return {
    text: JSON.stringify(payload, null, 2),
    commit: commits.length
      ? async () => {
        for (const commit of commits) await commit();
      }
      : undefined,
  };
}
